linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - unconvert
    - prealloc
  disable-all: false

linters-settings:
  gosec:
    excludes: []
  misspell:
    locale: US

issues:
  exclude-dirs:
    - build
    - vendor
  max-issues-per-linter: 0
  max-same-issues: 0
