linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - unconvert
    - prealloc
  disable-all: false

linters-settings:
  gosec:
    excludes:
      - G104
      - G304
      - G306
      - G404
  misspell:
    locale: US
    ignore-words:
      - strat
      - cancelled

issues:
  exclude-dirs:
    - build
    - vendor
  exclude-files:
    - ".*_test\\.go$"
  max-issues-per-linter: 0
  max-same-issues: 0
